name: CI/CD Portfolio

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - uses: supercharge/redis-github-action@1.1.0
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Laravel Setup
        run: |
          cp .env.example .env
          composer install
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: Migrate Database and Run Test
        env:
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_PASSWORD: password
        run: |
          php artisan migrate
          ./vendor/bin/pest

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy Production
  #       if: github.ref == 'refs/heads/master'
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: ./deploy-portfolio.sh
