name: Laravel Portfolio Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  portfolio-test:
		runs-on: ubuntu-latest
		
		services:
      # Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: db_test
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

		steps:
			- uses: actions/checkout@v2
			- uses: supercharge/redis-github-action@1.1.0
			- name: Laravel Setup
				run: |
					cp .env.example .env
					composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
					php artisan key:generate
					chmod -R 777 storage bootstrap/cache
			- name: Execute tests (Unit and Feature tests) via PHPUnit
				env:
					DB_CONNECTION: mysql
					DB_DATABASE: db_test
					DB_PORT: 33306
					DB_USER: root
					DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
				run: |
					php artisan migrate
					vendor/phpunit/phpunit/phpunit
